whatwg/meta

- GITHUB-TEAMS.md
> Document GitHub teams

- COMMITTING.md
Addresses: https://github.com/whatwg/meta/commit/b248294f7cb0be8c98574c41652d8ea5fe36a81e#commitcomment-25431719
> Editorial: Remove parenthetical italicization

- GITHUB-TEAMS.md
Addresses:
- https://github.com/whatwg/meta/issues/47#issuecomment-342737289
References:
- https://github.com/whatwg/meta/issues/47
> Editorial: Update teams and add brief description

- COMMITTING.md
Addresses: https://github.com/whatwg/meta/issues/37#issuecomment-342587779
> Editorial: Add single line character count "word" exception

- COMMITTING.md
- CONTRIBUTING.md
- GITHUB-TEAMS.md
- LABELS.md
- README.md
- TEAM.md
Fixes https://github.com/whatwg/meta/issues/48
Addresses:
- https://github.com/whatwg/meta/issues/48#issuecomment-342737876
> Editorial: Fix header capitalization congruence

- LABELS.md
> Labels: add "good first bug"

- LABELS.md
> Use "good first issue" as label

- COMMITTING.md
- CONTRIBUTING.md
- TEAM.md
> Encourage implementation bugs

- CONTRIBUTING.md
> Mention external principles in CONTRIBUTING.md

- CONTRIBUTING.md
- MAINTAINERS.md
See https://github.com/whatwg/whatwg.org/issues/197 for details.
> Document Review Drafts for maintainers

- CONTRIBUTING.md
Fixes https://github.com/whatwg/html/issues/3974.
> Document some aspects of whatpr.org

- MAINTAINERS.md
Closes https://github.com/whatwg/dom/issues/710.
> Maintainers should inform documentation

- COMMITTING.md
Better clarification of commit examples with most common use case.
Fixes: #97
> Meta: fix commit example

- CONTRIBUTING.md
As indicated at https://github.com/whatwg/html/pull/4878#issuecomment-533922439 contributors might miss they have to sign this.
> Mention Participant Agreement in CONTRIBUTING.md

- CONTRIBUTING.md
> Give folks filing issues some pointers

- GITHUB-TEAMS.md
> Add cross-origin isolation and triage teams

- COMMITTING.md
As these are lost to history, it really doesn't matter much.
> COMMITTING.md: remove branch advice

- LABELS.md
- labels.json
> Add the i18n-afrlreq label

- COMMITTING.md
It seems useful to have all somewhat special prefixes listed in a single place.
> COMMITTING: document RD prefix

- COMMITTING.md
> COMMITTING: only enforce length for commit title

- NEW-STANDARD.md
@domenic @foolip did I miss anything? I thought it would be useful to have this somewhere as we now have multiple candidates for new standards so we'll likely have to exercise this at some point.
> Add checklist for creating new standards

- MAINTAINERS.md
See https://github.com/whatwg/spec-factory/pull/35
> Add links to Deno and Node issue trackers

- COMMITTING.md
It has bitten us on the compat spec.
> Adjusts documentation about case sensitivity

- MAINTAINERS.md
- review.py
Fixes #253.
I tested this locally but did not test the PR creation. But, that code is unchanged, so maybe it'll be fine?
Python review appreciated, I don't write a lot.
> Merge "make review" scripts into review.py

- MAINTAINERS.md
Complements https://github.com/whatwg/spec-factory/pull/40.
> MAINTAINERS: use engine names

- LABELS.md
- labels.json
These are described in https://github.com/whatwg/meta/issues/290.
> Document stage: N labels

- labels.py
> Align labels.py with W3C changes

- GITHUB-TEAMS.md
Also fix various minor issues.
> Update the GitHub Team document

- LABELS.md
- labels.json
- labels.py
Closes #270 and helps with #297.
> Add integration and needs incubation labels
